name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17
    - name: Install dependencies
      run: yarn install --immutable
    - name: Install semantic-release extra plugins
      run: yarn add -D @semantic-release/changelog @semantic-release/git
    - name: Lint
      run: yarn lint && yarn prettier
    - name: Build
      run: yarn build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release